### ISSUE TITLE
No AMP template

### ISSUE THREAD

**Issue by jamesw6811** [TryGhost/Ease#13]
Would be really great to get an `amp.hbs` in this theme by default, instead of having to recreate ourselves.

**Comment by minimaluminium** [comment]
Hey @jamesw6811, `amp.hbs` isn't required to make AMP work. If there's no `amp.hbs`, the default one will be used. If you only want to customize the template, the file is required.

**Comment by jamesw6811** [comment]
> Hey @jamesw6811, `amp.hbs` isn't required to make AMP work. If there's no `amp.hbs`, the [default one](https://github.com/TryGhost/Ghost/blob/main/core/frontend/apps/amp/lib/views/amp.hbs) will be used. If you only want to customize the template, the file is required.

Thanks!
