### ISSUE TITLE
Parallax scrolling effect in Safari

### ISSUE THREAD

**Issue by dirkspahn** [TryGhost/Ease#15]
There seems to be a bug with the publication cover when you scroll the page in Safari (Mac). The lower placed content has a transparency.
<img width="835" alt="Screenshot 2021-04-08 at 19 43 17" src="https://user-images.githubusercontent.com/50478936/114072559-b395e080-98a2-11eb-9ca8-74f223f7ee37.png">

**Comment by minimaluminium** [comment]
Hey @dirkspahn, thanks for reporting. Fixed in https://github.com/TryGhost/Ease/commit/5a792e6420f26e7b266571fe3e1d28183a5b7345

**Comment by dirkspahn** [comment]
Hi Sodbileg,

Thank your for your quick response and the fix :)

Many regards and stay healthy, Dirk


> On 9. Apr 2021, at 07:27, Sodbileg Gansukh ***@***.***> wrote:
> 
> 
> Hey @dirkspahn, thanks for reporting. Fixed in 5a792e6
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 


-- 










web://contact GmbH - treffsichere Websites und Online-Marketing
Waldblumenstraße 48 | 75334 Straubenhardt
Amtsgericht Mannheim HRB 719226 | 
Geschäftsführerin Daniela Spahn
www.webcontact.de 
<http://www.webcontact.de> | Fon. 07082.948344 | Fax. 07082.948345
