### ISSUE TITLE
Translatable theme

### ISSUE THREAD

**Issue by clementduveau** [TryGhost/Ease#16]
This theme is "official" and really useful but it is not available in french.
I will fork this theme and make it translatable, with at leat fr and en implemented.

Is this something you could potentially merge ? As I will not have time to keep this theme up to date with the new features, I would like to contribute to the official theme.

**Comment by minimaluminium** [comment]
Hey there, you're very welcome to translate the theme or release your own translated themes! We're not ready to include translations by default in the theme at the moment.
