### ISSUE TITLE
Search doesn't work with Cyrillic (Russian, Ukrainian) text

### ISSUE THREAD

**Issue by solarfl4re** [TryGhost/Ease#20]
To reproduce:

- create a post with the title "Тест" ('test' in Russian).
- create another post with the title "Test".
- Try searching for "Тест" - nothing shows up.
- Search for "Test" - our post shows in the results.

Edit - issues:

- https://github.com/weixsong/elasticlunr.js/issues/76
- https://github.com/olivernn/lunr.js/issues/318

Possible solution - https://github.com/MihaiValentin/lunr-languages has support for Russian. Will give it a try.

**Comment by minimaluminium** [comment]
Hey @solarfl4re, sorry about the huge delay! We're not planning to add Cyrillic support to search function by default.

[Here](https://github.com/weixsong/lunr-languages) is a repo for elasticlunr.js language support. And [here](https://github.com/weixsong/elasticlunr.js/issues/22#issuecomment-245564338) is a helpful comment from the maintainer for integrating different language than English in the library.

Our [forum](https://forum.ghost.org/) is also a great place to get community support.

Thanks!
