### ISSUE TITLE
Disqus integration fails

### ISSUE THREAD

**Issue by robin-w-ford** [TryGhost/Ease#21]
Documentation states in order to enable Disqus to 
`Insert the Disqus shortname in partials/config.hbs file.`
This file doesnt exist.
Adding to comment.hbs has no effect either.
The only way i've been able to add is to post.hbs but comment box then takes full width.

**Comment by minimaluminium** [comment]
Hey @robin-w-ford,

When you paste the Disqus embed code into `comment.hbs`, make sure keep the layout related HTML. Just uncomment it by removing `{{!--` and `--}}`, and put the code between the tags.

```html
<div class="comment-container">
    <div class="container">
        <div class="comment container medium">
            Place your embed code here...
        </div>
    </div>
</div>
```

**Comment by robin-w-ford** [comment]
I had installed Ease via MarketPlace but looks like some other files were different so even doing this didn't display the comments section.
I downloaded and overwrote the theme using the code from GitHub and all now works as expected.
Might be worth updating the code/instructions on Ghost Marketplace
