### ISSUE TITLE
Search excerpt is undefined

### ISSUE THREAD

**Issue by zutrinken** [TryGhost/Ease#22]
Running ghost 4.33.1, the search only works for title and url, but excerpt stays undefined.

**Comment by minimaluminium** [comment]
Hey @zutrinken, I couldn't reproduce the issue. Is this something related with the mentioned Attila theme?

It'd help if you could elaborate more :)

**Comment by minimaluminium** [comment]
Couldn't reproduce this in Ease theme, closing the issue for now.
