### ISSUE TITLE
tags on home page sort by first uploaded, not date of publication.

### ISSUE THREAD

**Issue by LeeJMorel** [TryGhost/Ease#24]
![image](https://user-images.githubusercontent.com/46356258/176736850-a873718b-bba4-4edf-9c77-ce19114819f9.png)

The tag page is sorted by newest post first, but the home page features tags in reverse order. Any help would be appreciated!

**Comment by minimaluminium** [comment]
Hey @LeeJMorel,

The tags on the homepage are ordered alphabetically by name in ascending order which is the default behavior for tags.

This can be changed by adding order parameter in the [get helper](https://github.com/TryGhost/Ease/blob/7200e0a0fd9da4e67ba35e5c6871b75f71782bb4/index.hbs#L8).

More info here: https://ghost.org/docs/themes/helpers/get/#order
