### ISSUE TITLE
bug: search feature not working after adding content api key

### ISSUE THREAD

**Issue by rbrtbrnschn** [TryGhost/Ease#25]
Added the script from the readme to the header.
![image](https://user-images.githubusercontent.com/56562982/177542214-72d127e7-4ae6-4bb8-abd1-818a29b9dc83.png)

Made sure it's the right content api key.
![image](https://user-images.githubusercontent.com/56562982/177542329-db2bead3-35c9-452d-8a60-04806565e1f6.png)

It just doesnt show.
![image](https://user-images.githubusercontent.com/56562982/177543747-7f72ad8c-c8b7-44fc-b115-957877bfbcc8.png)

**Comment by minimaluminium** [comment]
Hey @rbrtbrnschn,

The instructions in the repo is outdated, follow the instructions on the theme's [about page](https://ease.ghost.io/about/). :)
