### ISSUE TITLE
search key field is missing?

### ISSUE THREAD

**Issue by endigma** [TryGhost/Ease#26]
![image](https://user-images.githubusercontent.com/34945114/181097932-43c53551-ce56-4870-8699-7bd520090407.png)

**Comment by endigma** [comment]
search bar is non functional until I remove `disabled` after which it works perfectly, what is the point of this?

**Comment by minimaluminium** [comment]
Hey @endigma, the search doesn't require a key anymore. Starting from v5.3.0, Ghost added a native search support and all our official themes support the feature as well. If it doesn't work on your site, make sure you're using the latest version of Ghost.

More on the native search: https://ghost.org/changelog/search/

**Comment by endigma** [comment]
It does work, the search bar has `disabled` attribute for some reason?

**Comment by endigma** [comment]
@minimaluminium 

![image](https://user-images.githubusercontent.com/34945114/181269213-065f2060-4f7c-4adf-9723-d6d2ef7d5ac1.png)

How is this possibly a versioning issue?

**Comment by endigma** [comment]
https://github.com/TryGhost/Ease/blob/81eefbc8a8799865c07e48f67f31d1f0a4b8e03a/default.hbs#L53

Perhaps because `disabled` is hardcoded into your theme?

**Comment by endigma** [comment]
you also still include `elasticlunr.js` and a bunch of code in `main.js` regarding this now defunct API based search.

**Comment by minimaluminium** [comment]
Good catch! The legacy code using `elasticlunr` is now removed from the codebase.

As for the `disabled` attribute, it has nothing to do with this issue "search key field is missing?". It's used for disabling the input, because it's used as a toggle for the native search input now.

**Comment by minimaluminium** [comment]
Now the search input is replaced with a non-input HTML element as it's only used as a toggle and we won't need an actual text input element for this. Should fix the issue if the search didn't work with the `disabled` attribute.
