### ISSUE TITLE
Search field is disabled (legacy code dependency?)

### ISSUE THREAD

**Issue by endigma** [TryGhost/Ease#27]
In `default.hbs`:

https://github.com/TryGhost/Ease/blob/81eefbc8a8799865c07e48f67f31d1f0a4b8e03a/default.hbs#L53

the search field is hardcoded to `disabled` state, which is never updated by JS as far as I can tell, this is visible in production latest ghost installs using latest ease theme. 

and the project still includes `elasticlunr.js` as well as search-relevant code in `main.js`.

this is the root cause of #26 which you slammed the door on before waiting for it to be actually resolved.

**Comment by minimaluminium** [comment]
`disabled` attribute is intentional. It disables the actual search input, because the input now acts as a toggle for the native search input.
