### ISSUE TITLE
Post cover images are cropped and blurred

### ISSUE THREAD

**Issue by TheodoreChu** [TryGhost/Ease#5]
Post cover images are cropped and blurred

Steps to reproduce:
1. Upload a large high-quality image (not from Unsplash) as the post image
2. Upload the same image in the body of the post

The post image is cropped and blurred compared to the image in the body.

I think this is because of the `post-image lazyload u-object-fit` class in `post-media.hbs`, but I am not sure: https://github.com/TryGhost/Ease/blob/master/partials/post-media.hbs#L5-L10

Compare this to post images in Casper: https://github.com/TryGhost/Casper/blob/master/partials/post-card.hbs#L7-L16

Is this fixable with code injections or does the theme need to be modified?

**Comment by minimaluminium** [comment]
Hey Theodore, the featured images are no longer cropped in https://github.com/TryGhost/Ease/commit/bdc9543b21c71bb2517df0c3e47085d3466efe51. Also I made sure the responsive image size is same as the container width, so there shouldn't be any blurriness.
