### ISSUE TITLE
Some issues with Ease on IE11

### ISSUE THREAD

**Issue by pysiak** [TryGhost/Ease#6]
Go to https://ease.ghost.io/ using IE11.
Doesn't display all right, fonts not loaded. Most likely all down to a few issues observedin the console.
Perhaps just some fixup polyfills are required.
![image](https://user-images.githubusercontent.com/2396137/103024800-d64cf500-4550-11eb-8222-4a2866e7e312.png)

Yeah, I know, IE11.

**Comment by minimaluminium** [comment]
Hey @pysiak, we're not supporting IE11 on our themes. Plus IE11's end of support by Microsoft was Nov 30, 2020.
